M48
; DRILL file {KiCad 6.0.4-6f826c9f35~116~ubuntu20.04.1} date Wed Jun 21 22:45:50 2023
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2023-06-21T22:45:50+00:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,6.0.4-6f826c9f35~116~ubuntu20.04.1
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C1.000
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C1.200
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T3C2.000
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T4C2.700
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T5C3.000
%
G90
G05
T1
X22.0Y9.1
X22.0Y7.1
X22.1Y4.975
X23.65Y10.05
X23.65Y4.95
X28.75Y10.05
X28.75Y4.95
T2
X22.475Y3.0
T3
X21.9Y11.6
T4
X8.5Y13.0
X8.5Y2.0
T5
X2.5Y15.0
X2.5Y0.0
X12.5Y15.0
X12.5Y0.0
X22.5Y15.0
X22.5Y0.0
T0
M30
