name: Kicad build

on:
  workflow_dispatch:
  
env:
  schema: "hw/sch_pcb/*.kicad_sch"
  board: "hw/sch_pcb/*.kicad_pcb"
  dir: "hw/out"
  kibot: "doc/assets/kibot"

jobs:
# checks
  ERC:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: INTI-CMNB/KiBot@master
        with:
          config: ${{ env.kibot }}/erc.kibot.yaml
          schema: ${{ env.schema }}
          board: ${{ env.board }}
          dir: ${{ env.dir }}
  DRC:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: INTI-CMNB/KiBot@master
        with:
          config: ${{ env.kibot }}/drc.kibot.yaml
          schema: ${{ env.schema }}
          board: ${{ env.board }}
          dir: ${{ env.dir }}
# documentation
  docs:
    runs-on: ubuntu-latest
    needs: [ERC]
    steps:
      - uses: actions/checkout@v2
      - uses: INTI-CMNB/KiBot@master
        with:
          config: ${{ env.kibot }}/docs.kibot.yaml
          schema: ${{ env.schema }}
          board: ${{ env.board }}
          dir: ${{ env.dir }}_docs
      - uses: actions/upload-artifact@v2
        if: ${{ success() }}
        with:
          name: ${{ github.event.repository.name }}_docs
          path: ${{ env.dir }}_docs/**
# fabrications
  gerbers:
    runs-on: ubuntu-latest
    needs: [DRC]
    steps:
      - uses: actions/checkout@v2
      - uses: INTI-CMNB/KiBot@master
        with:
          config: ${{ env.kibot }}/gerbers.kibot.yaml
          schema: ${{ env.schema }}
          board: ${{ env.board }}
          dir: ${{ env.dir }}_gerbers
      - uses: actions/upload-artifact@v2
        if: ${{ success() }}
        with:
          name: ${{ github.event.repository.name }}_gerbers
          path: ${{ env.dir }}_gerbers/gerbers/**
# cad
  cad:
    runs-on: ubuntu-latest
    needs: [DRC]
    steps:
      - uses: actions/checkout@v2
      - uses: INTI-CMNB/KiBot@master
        with:
          config: ${{ env.kibot }}/cad.kibot.yaml
          schema: ${{ env.schema }}
          board: ${{ env.board }}
          dir: ${{ env.dir }}_cad
      - uses: actions/upload-artifact@v2
        if: ${{ success() }}
        with:
          name: ${{ github.event.repository.name }}_cad
          path: ${{ env.dir }}_cad/**
# render
  render:
    runs-on: ubuntu-latest
    needs: [DRC]
    steps:
      - uses: actions/checkout@v2
      - uses: INTI-CMNB/KiBot@master
        with:
          config: ${{ env.kibot }}/render.kibot.yaml
          schema: ${{ env.schema }}
          board: ${{ env.board }}
          dir: ${{ env.dir }}_img
      - uses: actions/upload-artifact@v2
        if: ${{ success() }}
        with:
          name: ${{ github.event.repository.name }}_img
          path: ${{ env.dir }}_img/img/**
